
name: Foo

on:
  push:
    branches: [ master, 'release/foo/*' ]
    paths: [ 'services/foo/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'services/foo/**' ]
  workflow_dispatch:
    inputs:
      stage:
        description: Deployment Environment
        type: choice
        options:
          - dev
          - staging
          - v1
        required: true
      ref:
        description: Branch, Tag, or Commit
        type: string
        required: true

jobs:

  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
      - run: ./build.sh
      - run: ./test.sh

  dev:
    if: ${{ github.event.inputs.stage == 'dev' || (github.event_name == 'push' && github.ref_name == 'master') }}
    runs-on: ubuntu-latest
    environment: dev
    concurrency: foo/dev
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - run: echo ${{ github.event.inputs.ref || github.ref }}
      - run: ./build.sh
      - run: ./test.sh
      - run: ./deploy.sh

  staging:
    if: ${{ github.event.inputs.stage == 'staging' || (github.event_name == 'push' && startsWith(github.ref_name, 'release/foo')) }}
    runs-on: ubuntu-latest
    environment: staging
    concurrency: foo/staging
    permissions: write-all
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - run: echo ${{ github.event.inputs.ref || github.ref }}
      - run: ./build.sh
      - run: ./test.sh
      - run: ./deploy.sh
      - uses: EndBug/latest-tag@v1
        with:
          tag-name: deployed/foo/staging

  production:
    if: ${{ github.event.inputs.stage == 'v1' }}
    runs-on: ubuntu-latest
    environment: v1
    concurrency: foo/v1
    permissions: write-all
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - run: echo ${{ github.event.inputs.ref }}
      - run: ./build.sh
      - run: ./test.sh
      - run: ./deploy.sh
      - uses: EndBug/latest-tag@v1
        with:
          tag-name: deployed/foo/v1
