
name: Foo / CI / Production

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch, Tag, or Commit
        default: deployed/foo/staging
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: v1
    concurrency: foo/v1
    permissions: write-all
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - run: echo Deploying to $STAGE
      - run: ./build.sh
      - run: ./deploy.sh
      - uses: EndBug/latest-tag@v1
        with:
          tag-name: deployed/foo/v1
