
name: CI / Foo / Release

on:
  workflow_dispatch:
    inputs:
      stage:
        description: Stage
        default: staging
        required: true
        type: choice
        options:
          - dev
          - staging
          - v1
      ref:
        default: master
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'service/foo'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build
        run: ./build.sh

      - name: Deploy
        run: ./deploy.sh
