
name: CI / Foo / Release

on:
  workflow_dispatch:
    inputs:
      stage:
        description: Stage
        default: staging
        required: true
        type: choice
        options:
          - dev
          - staging
          - v1
      ref:
        default: master
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
      - run: ./build.sh
      - run: ./deploy.sh
