
name: CI / Foo / Release

on:
  workflow_dispatch:
    inputs:
      stage:
        description: Stage
        default: staging
        required: true
        type: environment
      ref:
        default: master
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.ref}}
      - run: ./build.sh
      - run: ./deploy.sh
