
name: Foo / Deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Release Branch
        required: true
      stage:
        description: Stage
        default: staging
        required: true
        type: choice
        options:
          - dev
          - staging
          - v1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: foo/${{ github.event.inputs.stage }}
    env:
      STAGE: ${{ github.event.inputs.stage }}
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.ref}}
      - run: echo Deploying to $STAGE
      - run: ./build.sh
      - run: ./deploy.sh
