
name: Foo / CI / Production

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Release Branch
        default: deployed/foo/staging
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: foo/v1
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.ref}}
      - run: echo Deploying to $STAGE
      - run: ./build.sh
      - run: ./deploy.sh
      - uses: EndBug/latest-tag@latest
        with:
          tag-name: deployed/foo/v1
