
name: Foo / CI / Staging

on:
  push:
    branches: [ 'release/foo/*' ]
  workflow_dispatch:
    inputs:
      ref:
        description: Release Branch
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: foo/staging
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.ref}}
      - run: ./build.sh
      - run: ./deploy.sh
      - name: Advance nightly tag
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/deployed/foo/staging",
              sha: context.sha
            })
