
name: Foo / CI / Dev

on:
  push:
    branches: [ master ]
    paths: [ 'services/foo/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'services/foo/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: foo/dev
    concurrency: foo/dev
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
      - run: ./build.sh
      - run: ./test.sh
      - run: ./deploy.sh
        if: ${{ github.event_name != 'pull_request' }}
        

