
name: Foo / CI / Staging

on:
  push:
    branches: [ 'release/foo/*' ]
  workflow_dispatch:
    inputs:
      ref:
        description: Release Branch
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: foo/staging
    defaults:
      run:
        working-directory: services/foo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.ref}}
      - run: ./build.sh
      - run: ./deploy.sh
      - uses: EndBug/latest-tag@latest
        with:
          tag-name: deployed/foo/staging
