
name: CI / Foo / Dev

on:
  push:
    branches: [ master ]
    paths: [ 'services/foo/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'service/foo/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'service/foo'
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ./build.sh

      - name: Test
        run: ./test.sh

      - name: Deploy
        if: github.event_name != 'pull_request'
        run: ./deploy.sh

