name: Foo / Release Branch

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Ref
        type: string
        required: true
        default: master

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.ref}}
      - run: |
          local BRANCH="release/foo/$(date +'%F-%s')"
          git switch -c $BRANCH
          git push -u origin $BRANCH


